backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  -
    name: "landing"
    label: "Landing"
    label_singular: "Landing"
    folder: "_landing"
    fields:
      - label: News
        name: news
        widget: "list"
        fields:
          - {label: "News tytuł", name: "news-title", widget: string}
          - {label: "News tło", name: "news-background", widget: image}
          - {label: "News link", name: "news-link", widget: string}
