backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  -
    name: "landing"
    label: "Landing"
    label_singular: "Landing"
    folder: "_landing"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Opis", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "landing"}
      - label: "News List"
        name: "news-list"
        widget: "list"
        allow_add: false
        fields:
          - label: "News"
            name: "news"
            widget: "object"
            allow_add: true
            fields:
              - {label: "News tytuł", name: "news-title", widget: string}
              - {label: "News tło", name: "news-background", widget: image}
              - {label: "News link", name: "news-link", widget: string}
