backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  -
    name: "landing"
    label: "Landing"
    label_singular: "Landing"
    folder: "_landing"
    create: false
    slug: ""
    fields:
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "landing"}
      - label: "Newsy"
        name: "news-list"
        label_singular: "News"
        widget: "list"
        allow_add: true
        fields:
          - name: "news"
            widget: "object"
            fields:
              - {label: "News tytuł", name: "title", widget: string}
              - {label: "News tło", name: "background", widget: image}
              - {label: "News link", name: "link", widget: string}
      - label: "Reklama góra"
        name: "advert-first"
        widget: "object"
        fields:
          - {label: "Reklama obrazek", name: "advert-first-image", widget: image}
          - {label: "Reklama link", name: "advert-first-link", widget: string}


  -
    name: "news-post"
    label: "News post"
    label_singular: "News"
    folder: "_news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "news"}
      - {label: "Treść", name: "content", widget: "markdown"}
