backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  -
    name: "landing"
    label: "Landing"
    folder: "src/landing"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "landing"}
      - label: "Newsy"
        name: "news_list"
        label_singular: "News"
        widget: "list"
        allow_add: true
        fields:
          - name: "news"
            widget: "object"
            fields:
              - {label: "News tytuł", name: "title", widget: string}
              - {label: "News tło", name: "background", widget: image}
              - {label: "News link", name: "link", widget: string}
      - label: "Reklama góra"
        name: "advert_first"
        widget: "object"
        fields:
          - {label: "Reklama obrazek", name: "advert_first_image", widget: image}
          - {label: "Reklama link", name: "advert_first_link", widget: string}


  -
    name: "events"
    label: "Wydarzenia"
    folder: "src/events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta Description(optimally 150 characters)", name: "meta_description", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Data publikacji", name: "publication_date", widget: date}
      - label: "Od"
        name: "from"
        widget: "date"
        default: ""
        format: "DD MMM YYYY"
      - label: "Do"
        name: "to"
        widget: "date"
        default: ""
        format: "DD MMM YYYY"

      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Obrazek", name: "image", widget: image}
      - {label: "Opis", name: "description", widget: "string"}
  -
    name: "reports"
    label: "Relacje"
    folder: "src/reports"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta Description(optimally 150 characters)", name: "meta_description", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Data publikacji", name: "publication_date", widget: date}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Obrazek", name: "image", widget: image}
      - {label: "Opis", name: "description", widget: "string"}

  -
    name: "informations"
    label: "Artinformacje"
    folder: "src/informations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta Description(optimally 150 characters)", name: "meta_description", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Data publikacji", name: "publication_date", widget: date}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Obrazek", name: "image", widget: image}
      - {label: "Opis", name: "description", widget: "string"}

  -
    name: "fairs"
    label: "Targi"
    folder: "src/fairs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta Description(optimally 150 characters)", name: "meta_description", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Data publikacji", name: "publication_date", widget: date}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Obrazek", name: "image", widget: image}
      - {label: "Opis", name: "description", widget: "string"}
